name: Commit Lint

on:
  pull_request:
    branches: [master]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint commits
        uses: wagoid/commitlint-github-action@v3

      - name: Block fixup commits
        uses: 13rac1/block-fixup-merge-action@v2.0.0
